/* autogenerated by Processing revision 1293 on 2023-11-07 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Kirmani_Shiraz_LabReport1 extends PApplet {

Cell cell1;

public void setup(){
  /* size commented out by preprocessor */;
  cell1 = new Cell();
  background(90, 90, 90);
}

public void draw(){
  //Comment out whichever method you do not want to use
  //cell1.move_random();
  cell1.move_perlin();
  cell1.display();
}
class Cell {
  //Declare variables
  float xpos, ypos, stepx, stepy, x, y, tx, ty = 0;
  
  //Constructor
  Cell (){
    //Initialise variables
    xpos = width/2;
    ypos = height/2;
    ty = height/2;
  }
  
    public void display(){
    //Cell colour and dimensions
    stroke(0);
    fill(255);
    ellipseMode(CENTER);
    ellipse(xpos, ypos, 10, 10);
    }
  
    public void move_random(){
      //Random motion using a novel movement algorithm (9 possible options)
      float stepx = PApplet.parseInt(random(3)) - 1;
      float stepy = PApplet.parseInt(random(3)) - 1;
      //To prevent the cell from moving off the screen, inverts the direction
      //if too far to the left or right respectively
      if (( xpos < 0) || ( xpos > width)){
         xpos -= stepx;
      }
      else{
         xpos += stepx;
      }  
      //if too low or high respectively
      if (( ypos < 0) || ( ypos > height)){
         ypos -= stepy;
      }
      else{
         ypos += stepy;
      }  
    }
    
    public void move_perlin(){
      //Random motion using Perlin noise
      //Mapping the Perlin noise value to the equivalent "posx" & "posy" values
      xpos = map(noise(tx), 0, 1, 0, width);
      ypos = map(noise(ty), 0, 1, 0, height);     
      //Increment time
      tx += 0.01f;
      ty += 0.01f;
    }
}


  public void settings() { size(500, 500); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Kirmani_Shiraz_LabReport1" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
